---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  gather_facts: true
  roles:
    - clickhouse

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  gather_facts: true
  roles:
    - lighthouse

- name: Install and configure Vector
  hosts: vector
  become: true
  gather_facts: true
  roles:
    - vector
