---
  el:
    hosts:
      centos7:
        ansible_connection: docker
      localhost:
        ansible_connection: local
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
      localhost:
        ansible_connection: local

  fed:
    hosts:
      fedora:
        ansible_connection: docker
